language: csharp
solution: UVACanvasAccess.sln
os: linux

branches:
  only:
    - master

install:
    - nuget restore UVACanvasAccess.sln

addons:
  apt:
    packages:
      - doxygen
      - graphviz

before_script:
  - cd UVACanvasAccess

script:
  - nuget pack UVACanvasAccess.csproj -Build -Properties Configuration=Release -Properties BuildVersion=$(date "+%s")
  - doxygen Doxyfile

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x ./deploy.sh && ./deploy.sh $GH_PACKAGES_USER $GH_PACKAGES_TOKEN
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    local_dir: UVACanvasAccess/docs/html
    github_token: $GH_REPO_TOKEN
    on:
      branch: master
